# Generated by Django 2.2 on 2022-03-18 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spellCheckerApp', '0006_auto_20220318_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='datetime_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 18, 20, 7, 20, 528341, tzinfo=utc)),
        ),
    ]
