# Generated by Django 2.2 on 2022-03-18 20:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spellCheckerApp', '0007_auto_20220318_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='datetime_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 18, 20, 15, 42, 414670, tzinfo=utc)),
        ),
    ]
